from .. import channelmonitor

TemporaryChannelMonitorUpdateErr = channelmonitor.TemporaryChannelMonitorUpdateErr
PermanentChannelMonitorUpdateErr = channelmonitor.PermanentChannelMonitorUpdateErr
Persist = channelmonitor.Persist